version: '3.8'

services:
  zimbra:
    container_name: app-zimbra
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      zimbra-network:
        ipv4_address: 172.25.2.1
    ports:
      - "82:80"
      - "444:443"
      - "25:25"
      - "143:143"
      - "993:993"
      - "110:110"
      - "995:995"
      - "389:389"
      - "636:636"
      - "7025:7025"
    volumes:
      - app-volume:/var/www/
    restart: always

networks:
  zimbra-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16

volumes:
  app-volume:
    driver: local